# Generated by Django 5.0.6 on 2024-05-31 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appchaosnews', '0003_alter_noticia_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='noticia',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='noticia',
            name='etiquetas',
            field=models.ManyToManyField(to='appchaosnews.etiqueta'),
        ),
    ]
