# Generated by Django 5.0.6 on 2024-06-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appchaosnews', '0004_etiqueta_alter_noticia_id_noticia_etiquetas'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='en_carrusel',
            field=models.BooleanField(default=False),
        ),
    ]
