# Generated by Django 5.0.6 on 2024-06-04 01:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appchaosnews', '0007_comentario_like'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('noticia', 'usuario')},
        ),
    ]
