# Generated by Django 5.0.6 on 2024-06-04 01:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appchaosnews', '0008_alter_like_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='contenido',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
