# Generated by Django 5.0.6 on 2024-06-09 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appchaosnews', '0013_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
