# Generated by Django 5.0.6 on 2024-06-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appchaosnews', '0015_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/default.png', null=True, upload_to='profile_pictures/'),
        ),
    ]
