# Generated by Django 5.0.6 on 2024-06-09 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appchaosnews', '0016_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
